stages:
  - build
  - test
  - sonarqube
build:
  script: "mvn compile"
  stage: build
test:
  script: "mvn test"
  stage: test
sonarqube:
  script: "mvn compile sonar:sonar -Dsonar.java.binaries=target/classes"
  stage: sonarqube
