variables:
  SONAR_LOGIN: "admin"
  SONAR_PASSWORD: "pimpas"
stages:
  - build
  - test
  - sonarqube
build:
  script: "mvn compile"
  stage: build
test:
  dependencies:
    - build
  script: "mvn test"
  stage: test
sonarqube:
  dependencies:
    - test
  script:
    - mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD
  stage: sonarqube
