stages:
  - build
  - test
  - sonarqube
build:
  script: "mvn compile"
  stage: build
test:
  dependencies:
    - build
  script: "mvn test"
  stage: test
sonarqube:
  dependencies:
    - test
  script: "mvn compile sonar:sonar -Dsonar.login='admin' -Dsonar.password='pimpas'"
  stage: sonarqube
