stages:
  - build
  - test
  - sonarqube
  - docker-image
  - docker-container
build:
  script: "mvn clean compile"
  stage: build
test:
  dependencies:
    - build
  script: "mvn test"
  stage: test
sonarqube:
  dependencies:
    - test
  script: "mvn -DskipTests install sonar:sonar"
  stage: sonarqube
docker-image:
  dependencies:
    - sonarqube
  script: "docker build -t rlstop-backend ."
  stage: docker-image
docker-container:
  dependencies:
    - docker-image
  script: "docker run -p 8080:8080 --name rlstop-backend --network rlstop -d rlstop-backend"
  stage: docker-container
